language: ruby
rvm:
  - 1.8.7
  - 1.9.2
env: RAILS_ENV=test
script: "bundle exec rake test:units"
before_script:
  - cp config/database.yml.example config/database.yml
  - "sed -ie 's/  adapter: mysql/  adapter: mysql2/g' config/database.yml"
  - "rake db:setup"
  - "sudo apt-get update"
  - "sudo apt-get install bzr cvs darcs git subversion"
  - "rake test:scm:setup:all"
branches:
  only:
    - master
notifications:
  email: false
